// Catálogo centralizado: atualize preços, textos e fontes somente neste array.
// Para adicionar um produto, copie um objeto, mantenha um id único e use uma categoria existente.
const BEESIDE_PRODUTOS = [
  {id:"roupa-01",nome:"Camiseta Masculina de Corrida Run Dry 500",marca:"Kiprun",categoria:"Roupas",subcategoria:"Camisetas",preco:99.99,precoOriginal:null,imagem:"assets/images/produto-indisponivel.webp",descricao:"Camiseta masculina desenvolvida para corrida e treinos intensos.",selo:"DESTAQUE",fonte:"Decathlon",urlFonte:"https://www.decathlon.com.br/camiseta-masculina-de-corrida-run-dry-500-branca-8861546-kiprun/p"},
  {id:"roupa-02",nome:"Short Masculino de Treino",marca:"Domyos",categoria:"Roupas",subcategoria:"Shorts",preco:89.99,precoOriginal:null,imagem:"assets/images/produto-indisponivel.webp",descricao:"Short leve para treino, com bolsos práticos e fechamento em zíper.",selo:"MAIS VENDIDO",fonte:"Decathlon",urlFonte:"https://www.decathlon.com.br/short-masculino-com-ziper-para-treino-120-preto-8547823-domyos/p"},
  {id:"roupa-03",nome:"Camiseta Masculina de Corrida Dry 500",marca:"Kalenji",categoria:"Roupas",subcategoria:"Camisetas",preco:69.99,precoOriginal:89.99,imagem:"assets/images/produto-indisponivel.webp",descricao:"Camiseta leve e respirável indicada para corrida.",selo:"OFERTA",fonte:"Decathlon",urlFonte:"https://www.decathlon.com.br/camiseta-masculina-de-corrida-dry-500-vermelho-8950666-kalenji/p"},
  {id:"acessorio-01",nome:"Mochila Esportiva Essential 17 L",marca:"Decathlon",categoria:"Acessórios",subcategoria:"Mochilas",preco:99.99,precoOriginal:null,imagem:"assets/images/produto-indisponivel.webp",descricao:"Mochila esportiva compacta com compartimento separado para calçados.",selo:"MAIS VENDIDO",fonte:"Decathlon",urlFonte:"https://www.decathlon.com.br/mochila-de-desporto-com-compartimento-para-calcado-17l-preto-8873326-decathlon/p"},
  {id:"acessorio-02",nome:"Mochila de Trilha Arpenaz 100 20 L",marca:"Quechua",categoria:"Acessórios",subcategoria:"Mochilas",preco:129.99,precoOriginal:null,imagem:"assets/images/produto-indisponivel.webp",descricao:"Mochila de 20 litros indicada para caminhadas e uso cotidiano.",selo:"NOVIDADE",fonte:"Decathlon",urlFonte:"https://www.decathlon.com.br/mochila-de-trilha-20l-arpenaz-100-bege-8955893-quechua/p"},
  {id:"acessorio-03",nome:"Bolsa Esportiva de Futebol Essential 20 L",marca:"Kipsta",categoria:"Acessórios",subcategoria:"Bolsas esportivas",preco:89.99,precoOriginal:null,imagem:"assets/images/produto-indisponivel.webp",descricao:"Bolsa esportiva resistente, com espaço separado para calçados.",selo:"DESTAQUE",fonte:"Decathlon",urlFonte:"https://www.decathlon.com.br/bolsa-esportiva-20-l-incolor-8580082-decathlon/p"},
  {id:"suplemento-01",nome:"Whey Protein Concentrado Pouch 900 g",marca:"Integralmédica",categoria:"Suplementos",subcategoria:"Proteínas",preco:227,precoOriginal:null,imagem:"assets/images/produto-indisponivel.webp",descricao:"Suplemento alimentar de proteína concentrada do soro do leite.",selo:"DESTAQUE",fonte:"Integralmédica",urlFonte:"https://www.integralmedica.com.br/whey-protein-concentrado-900g/p"},
  {id:"suplemento-02",nome:"Creatina 100% Pura Hardcore 300 g",marca:"Integralmédica",categoria:"Suplementos",subcategoria:"Creatina",preco:60,precoOriginal:null,imagem:"assets/images/produto-indisponivel.webp",descricao:"Suplemento alimentar de creatina monohidratada em pó.",selo:"MAIS VENDIDO",fonte:"Integralmédica",urlFonte:"https://www.integralmedica.com.br/kits"},
  {id:"suplemento-03",nome:"Protein Crisp Bar Ovomaltine — Caixa com 12 unidades",marca:"Integralmédica",categoria:"Suplementos",subcategoria:"Barras proteicas",preco:119,precoOriginal:null,imagem:"assets/images/produto-indisponivel.webp",descricao:"Caixa com 12 unidades de barra proteica sabor Ovomaltine.",selo:"NOVIDADE",fonte:"Integralmédica",urlFonte:"https://www.integralmedica.com.br/whey-protein-concentrado-900g/p"}
];
const PLACEHOLDER="assets/images/produto-indisponivel.png",moeda=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),slug=c=>c.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
// As fotografias reais ficam em assets/images. Este mapa mantém um arquivo correspondente para cada produto.
const BEESIDE_IMAGENS = {
  "roupa-01":"assets/images/C2.jpg",
  "roupa-02":"assets/images/R1.jpg",
  "roupa-03":"assets/images/C1.jpg",
  "acessorio-01":"assets/images/Mochila.jpg",
  "acessorio-02":"assets/images/M2.jpg",
  "acessorio-03":"assets/images/M3.jpg",
  "suplemento-01":"assets/images/S1.jpg",
  "suplemento-02":"assets/images/S2.jpg",
  "suplemento-03":"assets/images/S3.jpg"
};
BEESIDE_PRODUTOS.forEach(produto=>produto.imagem=BEESIDE_IMAGENS[produto.id]||PLACEHOLDER);
const favoritos=()=>JSON.parse(localStorage.getItem("beeside_favorites")||"[]");
// O desconto só aparece com preço original verificado e é calculado automaticamente.
function cartao(p,i){const d=p.precoOriginal?Math.round((1-p.preco/p.precoOriginal)*100):0,f=favoritos().includes(p.id);return `<article class="product-card" data-product-id="${p.id}"><div class="product-media"><span class="product-badge">${p.selo}${d?` · -${d}%`:""}</span><button type="button" class="fav-btn${f?" is-favorite":""}" data-favorite aria-label="Favoritar ${p.nome}" aria-pressed="${f}">♥</button><img src="${p.imagem}" alt="${p.nome}, ${p.marca}" ${i>2?'loading="lazy"':''} onerror="this.onerror=null;this.src='${PLACEHOLDER}'"></div><div class="product-info"><span class="product-category">${p.marca} · ${p.categoria}</span><h3 class="product-name">${p.nome}</h3><div class="product-price">${p.precoOriginal?`<span class="price-old">${moeda(p.precoOriginal)}</span>`:""}<span class="price-new">${moeda(p.preco)}</span></div><div class="product-actions"><button class="btn btn-add" data-add>Adicionar ao carrinho</button><button class="details-link" data-details>Ver detalhes</button></div></div></article>`}
function adicionar(p){const c=beesideGetCart(),i=c.find(x=>x.slug===p.id);if(i)i.quantity++;else c.push({slug:p.id,name:p.nome,brand:p.marca,price:p.preco,image:p.imagem,quantity:1});localStorage.setItem("beeside_cart",JSON.stringify(c));beesideUpdateCartCount()}
function detalhes(p){document.querySelector("#productModalContent").innerHTML=`<button class="modal-close" data-close aria-label="Fechar">×</button><img src="${p.imagem}" alt="${p.nome}, ${p.marca}" onerror="this.onerror=null;this.src='${PLACEHOLDER}'"><div><span class="product-category">${p.marca} · ${p.categoria} / ${p.subcategoria}</span><h2>${p.nome}</h2><p>${p.descricao}</p><strong>${moeda(p.preco)}</strong><small>Valor usado apenas como referência acadêmica.</small><a class="btn btn-primary" href="${p.urlFonte}" target="_blank" rel="noopener noreferrer">Consultar produto na fonte (${p.fonte})</a></div>`;document.querySelector("#productModal").showModal()}
function renderizar(t=""){const b=t.trim().toLocaleLowerCase("pt-BR");document.querySelectorAll(".product-grid").forEach(g=>{const l=BEESIDE_PRODUTOS.filter(p=>slug(p.categoria)===g.dataset.category&&`${p.nome} ${p.marca} ${p.subcategoria}`.toLocaleLowerCase("pt-BR").includes(b));g.innerHTML=l.map(cartao).join("");g.closest(".product-section").hidden=!l.length;g.previousElementSibling.querySelector("span").textContent=`${l.length} produto${l.length===1?"":"s"}`})}
document.addEventListener("DOMContentLoaded",()=>{renderizar();document.querySelectorAll("#searchInput,.mobile-search input").forEach(i=>i.addEventListener("input",()=>renderizar(i.value)));document.querySelector(".search-form")?.addEventListener("submit",e=>e.preventDefault());document.querySelector("main").addEventListener("click",e=>{const c=e.target.closest(".product-card");if(!c)return;const p=BEESIDE_PRODUTOS.find(x=>x.id===c.dataset.productId);if(e.target.closest("[data-add]"))adicionar(p);if(e.target.closest("[data-details]"))detalhes(p);if(e.target.closest("[data-favorite]")){let f=favoritos();f=f.includes(p.id)?f.filter(x=>x!==p.id):[...f,p.id];localStorage.setItem("beeside_favorites",JSON.stringify(f));renderizar(document.querySelector("#searchInput")?.value||"")}});document.querySelector("#productModal").addEventListener("click",e=>{if(e.target.hasAttribute("data-close")||e.target.id==="productModal")e.currentTarget.close()})});
